package com.silentsupply.analytics.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * Response DTO representing revenue data for a single product.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ProductRevenueResponse {

    /** Product ID. */
    private Long productId;

    /** Product name. */
    private String productName;

    /** Total revenue generated by this product. */
    private BigDecimal revenue;

    /** Number of orders for this product. */
    private long orderCount;
}
