package com.silentsupply.proposal;

import com.silentsupply.common.entity.BaseEntity;
import com.silentsupply.rfq.Rfq;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * Represents an individual proposal (offer) within an RFQ negotiation.
 * Can be submitted by the buyer or auto-generated by the negotiation engine.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "proposals")
public class Proposal extends BaseEntity {

    /** The RFQ this proposal belongs to. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rfq_id", nullable = false)
    private Rfq rfq;

    /** Who created this proposal. */
    @Enumerated(EnumType.STRING)
    @Column(name = "proposer_type", nullable = false)
    private ProposerType proposerType;

    /** Proposed price per unit. */
    @Column(name = "proposed_price", nullable = false, precision = 15, scale = 2)
    private BigDecimal proposedPrice;

    /** Proposed quantity. */
    @Column(name = "proposed_qty", nullable = false)
    private int proposedQty;

    /** Proposed delivery time in days. */
    @Column(name = "delivery_days", nullable = false)
    private int deliveryDays;

    /** Current proposal status. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private ProposalStatus status = ProposalStatus.PENDING;

    /** Which negotiation round this proposal belongs to. */
    @Column(name = "round_number", nullable = false)
    private int roundNumber;

    /** Reason code for rejection or counter (e.g., "PRICE_BELOW_FLOOR"). */
    @Column(name = "reason_code")
    private String reasonCode;
}
