package com.silentsupply.proposal;

/**
 * Identifies who created a proposal within the RFQ negotiation.
 */
public enum ProposerType {

    /** Proposal submitted by the buyer. */
    BUYER,

    /** Counter-proposal generated by the negotiation engine. */
    SYSTEM
}
